CREATE TABLE USERS
(
    USER_ID NUMBER(19,0) PRIMARY KEY NOT NULL,
    USER_ISACTIVE NUMBER(1,0),
    USER_EMAIL VARCHAR2(255),
    USER_LOGIN VARCHAR2(255),
    USER_NAME VARCHAR2(255),
    USER_PIBY VARCHAR2(255),
    USER_PID DATE,
    USER_PN VARCHAR2(255),
    USER_PS VARCHAR2(255),
    USER_PASSWORD VARCHAR2(255),
    USER_PATRONYMIC VARCHAR2(255),
    USER_SURNAME VARCHAR2(255)
);

CREATE TABLE USER_ROLE
(
    USER_ID NUMBER(19,0) NOT NULL,
    ROLES VARCHAR2(255),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);
